# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hkaavvCZV1nDS2_uOuQMh30otjWfIlSL
"""

!pip install openai

import openai


api_key = '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'


openai.api_key = api_key


def generate_questions(prompt, num_questions=5, max_tokens=50):
    response = openai.Completion.create(
        engine="text-davinci-002",  # Choose an appropriate engine
        prompt=prompt,
        max_tokens=max_tokens,  # Adjust the max tokens as needed
        n=num_questions  # Fixed number of questions to generate
    )

    generated_questions = [question['text'].strip() for question in response.choices]
    return generated_questions

user_prompt = input("Enter the text for which you want to generate questions: ")

# Generate questions based on user input (fixed number of 2 questions)
generated_questions = generate_questions(user_prompt)

# Print the generated questions
print("\nGenerated Questions:")
for i, question in enumerate(generated_questions):
    print(f"{i + 1}) {question}")